### ISSUE TITLE
不报错,但是没效果

### ISSUE THREAD

**Issue by Weltolk** [chajianku/mok_bgimg#1]
请问还维护吗

**Comment by chajianku** [comment]
你好 mok开头的插件请联系@mokeyjay [i@mokeyjay.com]
wmzz开头的插件请联系@Kenvix [kenvix@qq.com]

**Comment by kenvix** [comment]
你好，我个人已不再维护 `wmzz_` 系列插件，这些插件都已以GPL协议开源，社区可自行维护
~~代码实在太屎了~~

**Comment by Weltolk** [comment]
> 你好 mok开头的插件请联系@mokeyjay [[i@mokeyjay.com](mailto:i@mokeyjay.com)] wmzz开头的插件请联系@kenvix [[kenvix@qq.com](mailto:kenvix@qq.com)]

好的,谢谢

**Comment by Weltolk** [comment]
> 你好，我个人已不再维护 `wmzz_` 系列插件，这些插件都已以GPL协议开源，社区可自行维护 ~代码实在太屎了~

好的,谢谢
